version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    ports:
      - "5432:5432"
    restart: always
    environment:
        POSTGRES_PASSWORD: "admin"
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "ticketing-app"
    volumes:
      - initdb:/var/lib/postgresql/data
    networks:
        - webnet
  ticketing-app:
    build: .
    container_name: ticketing-app
    ports:
      - "8080:8080"
    networks:
        - webnet
    depends_on:
        - mypostgres
networks:
  webnet:
    driver: bridge
volumes:
  initdb:

